# base image
FROM node:lts-alpine

ENV NODE_ENV development

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY . /app/
RUN npm install --silent
WORKDIR /app

CMD [ "npm", "run", "start" ]